### ISSUE TITLE
Documentation error: Melee dpad = left analog stick @ 25% tilt? But it's 127/255...

### ISSUE THREAD

**Issue by NintendoManiac64** [libertyernie/Nintendont#10]
The README.md says that Melee's dpad = left analog stick at 25% tilt, but it's using 127/255 which is 50% tilt is it not?

**Comment by libertyernie** [comment]
https://github.com/libertyernie/Nintendont/blob/eeb81b6a34ed51d4b9afc68b3edf89b84857e33e/loader/source/ppc/PADReadGC/source/PADReadGC.c#L284C3-L284C16

Looks like it's 25% in this build. Should it be 50%?

**Comment by NintendoManiac64** [comment]
> https://github.com/libertyernie/Nintendont/blob/eeb81b6a34ed51d4b9afc68b3edf89b84857e33e/loader/source/ppc/PADReadGC/source/PADReadGC.c#L284C3-L284C16
> 
> Looks like it's 25% in this build. Should it be 50%?

Oh that's funny. It looks like when I originally suggested 191/255, you instead used a value of 95. And then when I said it was too sensitive and suggested a value of 127/255, you instead used a value of 63:

- https://github.com/libertyernie/Nintendont/issues/2

So I guess the documentation actually is correct. I thought the GC analog stick values were 8 bit, but are they actually 7 bit?

**Comment by libertyernie** [comment]
Ah, that's a good point. I bet 0x3F is 50% (because -0x3F would be in the other direction and there's 8 bits for the whole access). I'll update the readme
