### ISSUE TITLE
Grey @ 2023-12-25 - stuck at GC_R 255/255 analog + GC_R digital if you switch from non-pro CC to CC pro

### ISSUE THREAD

**Issue by NintendoManiac64** [libertyernie/Nintendont#11]
Tested with Mario Sunshine.

If you boot the game with a standard non-pro CC connected and then, once you're actually in-game with FLUDD, if you unplug and switch to a CC pro, you will be constantly squirting water while standing in place even when not pressing anything on the physical CC pro controller, implying that it's constantly transmitting GC_R 255/255 analog + GC_R digital.

**Comment by libertyernie** [comment]
I think I noticed this with Mario Kart once too when I tried to switch. I'm not sure if there's some sort of bug in Nintendont somewhere, or if it has something to do with the Wii itself - I'd guess the former.

**Comment by NintendoManiac64** [comment]
I suppose the obvious thing for me to do is test on stock Nintendont; I'll be sure to do that at some point.

**Comment by NintendoManiac64** [comment]
I can confirm that this does not occur in the stock precompiled version of Nintendont available on 2023-12-30.

**Comment by libertyernie** [comment]
Do you know if this happens on the green build? I'd guess that it does (I just don't have Mario Sunshine available to test, but there's other ways I could check, I'm sure.) If not, it must be something exclusive to the gray one.

**Comment by NintendoManiac64** [comment]
Wait, is the green build based of the navy build with the custom controls and stuff, or is it based off the grey build with no custom stuff?

Also, to be clear, are you wanting me to still test the actual classic controller swapping in the green build and not anything regarding 360 controller stuff?

**Comment by NintendoManiac64** [comment]
It does not happen in the green build.

Smash Bros Melee is probably another easy game to test this with.

**Comment by libertyernie** [comment]
Oh, good point. I always forget Melee had analog shields. If it is just in the gray build, I imagine I should be able to fix it.

**Comment by NintendoManiac64** [comment]
Solved on 2024-01-19
