### ISSUE TITLE
Grey @ 2023-12-25 - CC-pro_R (and maybe also L?) is only GC_R digital, not also a GC_R 255/255 analog press

### ISSUE THREAD

**Issue by NintendoManiac64** [libertyernie/Nintendont#13]
Tested with Mario Sunshine.

Simply put, if you press R on the CC pro, Mario does not squirt any water and instead stands in place which, as I documented in #4, is what happens if you press the physical GC_R digital button inside of the controller without also sliding the internal GC_R analog slider.

(note to self: if/when this gets fixed, be sure to also test on a non-pro CC that has had its analog springs removed)

**Comment by libertyernie** [comment]
I thought `LI_ANALOG_SHOULDER_FULL` would take care of this but I guess it doesn't because the mapping is a bit different. Shouldn't be hard to fix.

Same thing would happen on a GameCube controller with the spring removed, wouldn't it? (Not that we have to support that.)

**Comment by NintendoManiac64** [comment]
That being said, I have considered re-mentioning that sort of thing upstream (this time with an example video) after it was misunderstood and closed the first time around, so it's at least hypothetically possible that it might get implemented even for GameCube controllers.

**Comment by NintendoManiac64** [comment]
Solved on 2024-01-19
