### ISSUE TITLE
045e_028e.ini file is required for 360 controller support on the 'green' build; either include a link or the file itself

### ISSUE THREAD

**Issue by NintendoManiac64** [libertyernie/Nintendont#14]
Xbox 360 controller support doesn't work unless the 045e_028e.ini file is present in the `sd:/controller/` folder.

So it might be best to either include a copy or to link to the pre-existing provided one:

- https://raw.githubusercontent.com/revvv/Nintendont-XBOX360/master/controllerconfigs/045e_028e.ini

**Comment by NintendoManiac64** [comment]
This is now present with build 2024-01-19 along with a note saying that it's required, but maybe add to the note something about tweaking the `EndpointOut=` value as specified in the actual ini file if your controller is blinking and/or rumble doesn't work.

**Comment by libertyernie** [comment]
Thanks, just added it.
