### ISSUE TITLE
Custom button mapping for Smash Bros Melee

### ISSUE THREAD

**Issue by NintendoManiac64** [libertyernie/Nintendont#2]
Build off of "Custom build 2023-01-21-B" (being sure to include the Xbox variant as well) and add to issues #3 and #4

- "small" L button on CC/pro = GC_L analog press @ 63/255
- "small" R button on CC/pro = GC_Z

- CC/pro_dpad = GC_left-stick @ 191/255 tilt
- CC/pro_select/minus = GC_dpad-up

**Comment by libertyernie** [comment]
What should the "big" buttons do in this case? Should they be the same as the "small" ones, or map to the original buttons?

**Comment by NintendoManiac64** [comment]
By "_Build off of "Custom build 2023-01-21-B"_" I mean to use its configuration as the starting point and then include the aforementioned listed changes/additions.

(this is also what I mean on the other issue tickets I opened)

**Comment by libertyernie** [comment]
Sounds good.

Mind if I disable all button mappings for the nunchuk? I don't know if you ever use it with Nintendont, but I don't, and it would probably free up enough space

**Comment by NintendoManiac64** [comment]
I'd say to only do that if you don't really see any other way to free up space.

**Comment by libertyernie** [comment]
I think I might try rewriting the GamePad mapping code by mapping it to a CC Pro and then calling the Classic Controller code from there - if that works, it'll help. I don't remember if I still have the homebrew on my Wii U that lets me use the GamePad on the Wii side, but hopefully I can figure that out again to test.

**Comment by libertyernie** [comment]
I can't get the Wii U VC injector to work anymore (I think this is the same one I used a few years ago; maybe it's because of eShop changes?) Are you able to test GamePad support? If not, I think I'll take it out - I don't want to make changes to code I can't test - and leave nunchuk support in.

**Comment by NintendoManiac64** [comment]
For the intended user(a family friend), gamepad support is going to be more important than nunchuck support since it'll be used on a Wii U.

So if you need to remove nunchuck support instead, then go right ahead.  This also means that the custom bust-a-move settings might be able to be slimmed down since I *think* you also made alterations to the nunchuck's analog stick (don't quote me on this though).

**Comment by libertyernie** [comment]
Try this one out:

https://github.com/libertyernie/Nintendont/releases/tag/v20230331

If the GamePad doesn't work (and I can't find a way to fix it), I'll put the old GamePad code back and take Nunchuk out.

**Comment by NintendoManiac64** [comment]
Uhh, well unfortunately I don't actually have a Wii U myself, so I can't actually test it.  The gamepad function is, as mentioned, for a family friend that has a Wii U, so I'd only be able to test this if/when ever I see them again.

For that reason, I don't suppose it'd be feasible to make copies of both?

On the subject of size constraints, wouldn't it be wise to also make sure that you have enough room for the Xbox 360 controller build as well?

**Comment by libertyernie** [comment]
I think this should work - I was able to fit the Xbox controller code in just barely without taking the nunchuk code out, by removing some leftover uncalled gamepad code I'd put in.

https://github.com/libertyernie/Nintendont/releases/tag/v20230401

I did test Classic Controller and Classic Controller Pro and those seem to work fine.

**Comment by NintendoManiac64** [comment]
> CC/pro_dpad = GC_left-stick @ 191/255 tilt

It would seem that this is too sensitive... rather than 3/4, let's try exactly half instead, i.e. 127/255, alright?

**Comment by NintendoManiac64** [comment]
127/255 works great!

But I wonder if we can consolidate *onl*y the left & right Dpad/analog stick values between Melee and Mario Kart Double Dash in order to save space as I've mentioned here:

- https://github.com/libertyernie/Nintendont/issues/6#issuecomment-1803024810

**Comment by NintendoManiac64** [comment]
Anyway, we can probably close this specific issue since I think everything's fine with Melee.
