### ISSUE TITLE
Custom button mapping for Spy Hunter (GSHE5D and GSHP5D)

### ISSUE THREAD

**Issue by NintendoManiac64** [libertyernie/Nintendont#3]
Build off of "Custom build 2023-01-21-B" (being sure to include the Xbox variant as well) and add to issues #2 and #4

- "small" R button on CC/pro = GC_Z+GC_R
- "small" L button on CC/pro = GC_Z+GC_L

- CC/pro_X = GC_Y
- CC/pro_Y = GC_X

　
**OPTIONAL** (leave out if it saves space in Nintendont)
- CC/pro_select/minus = GC_X

**Comment by NintendoManiac64** [comment]
I think I might have made a typo or two on this button arrangement and mixed up a couple of the Ls and Rs...

Amusingly though, the actual result in build 2023-10-30 seems to not be what I typo'd nor what I had originally intended, but a third configuration altogether.

So I've reworked the listed custom controls for this game, and the end result should actually be something that takes up less space in Nintendont (in particular I've removed the custom mapping for the "big" L button on CC/pro).

Also, if it saves space in Nintendont, you can optionally leave out the `CC/pro_select/minus = GC_X`

**Comment by NintendoManiac64** [comment]
Apologies for the delay; not only did I not realize you had posted an updated build but I only just got around to testing it.

Anyway, the controls are still messed up, but in a different way—the R and ZR buttons (on both CC and CC-Pro) straight up do nothing, but all other controls seem fine (including L and ZL on both CC and CC-Pro).

　
**REMINDER TO SELF**: When a revised version gets posted, make sure to also confirm that the analog shoulder buttons on the non-pro CC work correctly!

**Comment by libertyernie** [comment]
So both L buttons should activate L, both R buttons should activate R, but the small ones should also activate Z? I just checked Spy Hunter's manual and that would seem to make sense to me. I'll see if I can find a way to test it.

**Comment by NintendoManiac64** [comment]
Yup! Back when I played it, the control scheme was maddening and I kept mixing up what "fire defense/secondary weapon" was. I'm thinking this was very much designed for the PS2-style with 4 shoulder buttons, not three.

**Comment by NintendoManiac64** [comment]
Build 2023-12-09 works well.

The only minor tweak I'd mention is that it requires you to fully press in the analog shoulder buttons on the non-pro CC. Think we can do the thing you just did on Mario Kart Double Dash where you don't have to push the button in all the way? (from what I can remember, the game doesn't even use the analog functionality of the shoulder buttons)

**Comment by NintendoManiac64** [comment]
Everything in Spy Hunter seems fine on Navy @ 2023-12-25.
