### ISSUE TITLE
Custom button mapping for Mario Sunshine

### ISSUE THREAD

**Issue by NintendoManiac64** [libertyernie/Nintendont#4]
- "small" L button on CC/pro = GC_L analog press @ 255/255 (this *must* be an analog press, not a digital press!)
- "small" R button on CC/pro = GC_R analog press @ 255/255 + GC_R digital press

- "large" R button on CC pro *only* = GC_R analog press @ 255/255 (this *must* be an analog press, not a digital press!)

You can optionally set any or all of the above analog presses to 254/255 if that's easier on you for whatever reason since that will also work as confirmed with the existing builds.

And due to the mod we've previously done where a digital button press for GC_L and GC_R also sends the corresponding 255/255 analog shoulder button press, you could optionally set the "small" R button on CC pro to *only* be `GC_R digital press` and leave out the analog press for that button specifically and it'd still work fine, so if using a digital press saves space then that may actually be more ideal.

...also, I previously forgot that non-pro CC already had analog shoulder buttons, but the November 2023 custom button configs stripped that out for Mario Sunshine and Luigi's Mansion. Whoops!

**Comment by NintendoManiac64** [comment]
It would seem that I forgot to account that the "big" and "small" L buttons need to be reversed for these two games unlike the R/ZR buttons; that is:

- "large" L button on CC/pro = GC_L digital press

- "small" L button on CC/pro = GC_L analog press @ 254/255

I've modified the first post accordingly.

**Comment by NintendoManiac64** [comment]
Unfortunately we're going to have to separate Luigi's Mansion and Mario Sunshine. Turns out the games to some funny business whereby shoulder button digital presses and 255/255 analog shoulder button presses aren't the same thing, and the digital button presses only work if you're also doing a 255/255 analog shoulder button press (and, in the case of Luigi's Mansion, this only works if you do the analog shoulder button press followed by a digital shoulder button press rather than at the same time).

So I've renamed this to just be for Mario Sunshine and have revamped the controls accordingly.

...also, I previously forgot that non-pro CC already had analog shoulder buttons, but the custom button config stripped that out for Mario Sunshine and Luigi's Mansion. Whoops!

**Comment by libertyernie** [comment]
I don't think we even need to check to make sure we're using the Pro here - on an original Classic Controller, the only way "large R" would register as "pressed" is if was all the way down, and therefor there's also a full analog press. Does that sound right?

**Comment by NintendoManiac64** [comment]
The issue was that, in the previous build, it canceled out the analog functionality of the original classic controller's shoulder buttons.  While the important functionality was retained via the use of our custom "small" shoulder buttons mapping, it was less-than-ideal for people trying to have a more "proper" experience.

**Comment by libertyernie** [comment]
I'll see if I can find a way to avoid cancelling them out if I don't have to.

**Comment by NintendoManiac64** [comment]
Good news—build r2023-12-09 got everything working!

There are just two minor tweaks to be made but, at the very least, the current build has the actual games be playable.

　
For Mario Sunshine, I made a minor derp-up and swapped the controls for small and big R buttons. The thing is, I'm trying to match the R & ZR controls used in Mario 3D All Stars which has the big R button as running squirt:

- https://www.destructoid.com/heres-how-all-of-the-new-switch-controls-work-for-super-mario-3d-all-stars/

So, once again, I've fixed the first post accordingly.

**Comment by libertyernie** [comment]
I'll do that in my next build.

Do you think it might make sense to only apply custom controls for Sunshine when using the Classic Controller Pro? Or should it be for both, like the others? I haven't played it that much and especially not on a Classic Controller where the analog buttons - although analogous to what the GameCube has - have less travel to them.

**Comment by NintendoManiac64** [comment]
Although the analog shoulder buttons on the non-pro CC have less travel, that is not at all an issue because, for Mario Sunshine, all you really need to properly play the game is a full-click and the point right before a click.

But it's fine to only apply custom mappings to only the CC pro if you want. Presumably this would result in non-pro CC getting the default "customized" controls we normally use, where ZR/ZL on the non-pro CC are a half-press GC_R/GC_L?

**Comment by libertyernie** [comment]
I think it would, yeah. I'll give that a try

**Comment by libertyernie** [comment]
Here's the latest build you can try:

https://github.com/libertyernie/Nintendont/releases/tag/v20231225

**Comment by NintendoManiac64** [comment]
Everything in Mario Sunshine seems fine on Navy @ 2023-12-25.
