### ISSUE TITLE
Custom button mapping for Mario Kart: Double Dash!!

### ISSUE THREAD

**Issue by NintendoManiac64** [libertyernie/Nintendont#6]
- Y on CC/pro = GC_R digital press + GC_L digital press

**ALSO**: When CC/pro_Y is held, any horizontal movement on the CC/pro's left analog stick should also transmit a GC_A (this is because, when holding GC_R and GC_L at the same time, steering inputs do nothing unless you're also holding A)

If that takes up unnecessary memory, then you can instead just make CC/pro Y = GC_R+GC_L+GC_A instead; I was just trying to keep the player from accelerating forward if/when they were trying to pivot/rotate instead.

　
- "large" L button on CC/pro = GC_X

- "large" R button on CC-pro *only* = GC_R digital press

MK:DD!! does not seem to actually use the analog functionality of the shoulder buttons and yet requires you to fully press the button until it "clicks". Therefore, on non-pro CC, both the "large" L and "large" R buttons should ideally mimic what we've done with Midway Arcade Treasures 3 whereby you don't need to fully press a shoulder button to activate the corresponding button action.

- "small" L button on CC/pro = GC_Z

- "small" R button on CC/pro = GC_Z

- Dpad_left on CC/pro = GC_L digital press + GC_left-analog left @ 100/255

- Dpad_right on CC/pro = GC_R digital press + GC_left-analog right @ 100/255

- Dpad_up on CC/pro = GC_X + GC_left-analog up

- Dpad_down on CC/pro = GC_X + GC left-analog down

To clarify, for the last four, I'm wanting two GC "buttons" to be mapped to a single CC/pro button.

Lastly, GC_X does the same thing as GC_Y so, if for whatever reason you would rather use the Y button for this mapping, then you can do that.

**Comment by libertyernie** [comment]
I added code to handle these mappings, but the binary is now 58 bytes too large. It looks like the most I can add is a single button mapping (on top of what the 2023-04-01 build has) before I start having to remove other things in the file.

**Comment by NintendoManiac64** [comment]
So are you saying that, because it's 58 bytes too large, the current 2023-05-07 code is not in a usable state and we first need to remove something(s) to then get it to a usable state?

Or are you saying that the current 2023-05-07 code *is* in a usable state and that, to do anything additional, we need to remove stuff?

**Comment by libertyernie** [comment]
The former. (The nunchuk configs are still there and could be removed, or
let me know if you have other ideas)

**Comment by NintendoManiac64** [comment]
Sorry for the major delay but, yes, removing the nunchuck config should be fine.  My friend only just got a replacement controller so the derpy nunchuck configurations shouldn't be needed anymore.

After this, I don't suppose we have enough room to fit anything more (outside of whatever it is that issue #7 is asking about)? There's one or two last sort of "optional" thing I was wanting, i.e. a configuration that only some people would want to use, and shouldn't always be "carried forward" for any possible future tweaks.

**Comment by libertyernie** [comment]
If something is for a special build of Nintendont (like a different .dol), then it should be possible to find a control scheme we don't need in that specific case in order to make room.

**Comment by NintendoManiac64** [comment]
Turns out that using the R or L button on their own isn't really used in the menus at all, so we should be able to make left and right on the Dpad work even in the menus if we simply add a bit of an analog stick tilt (though I'm uncertain how much; it seems to need a bit less than half, maybe 40%?)

That being said, we're already using 127/255 (aka 50%) for Smash Bros Melee, so I don't suppose we're able to save space if we had both Melee and Double Dash using the same value specifically for left & right Dpad/analog stick (but *not* up & down Dpad/analog stick)?

But if we're not able to save space by consolidating, then I'd prefer trying something like 100/255 to start off with, i.e.:

- Dpad_left on CC/pro = GC_L digital press + GC_left-analog left @ 100/255

- Dpad_right on CC/pro = GC_R digital press + GC_left-analog right @ 100/255

**Comment by libertyernie** [comment]
Any reason left and right can't be a full tilt, like up and down are? If all four directions are the same amount of tilt, I can reuse part of the code that Melee and Four Swords Adventures use. (Although this does override the actual analog stick completely while the D-pad is pressed)

Although, I might be able to tweak the code a little to use different values for up/down and left/right too.

**Comment by NintendoManiac64** [comment]
Sure we can try a full tilt for left & right as well.

**Comment by libertyernie** [comment]
What's the reason for mapping L and R on GameCube to the left and right D-pad presses on CC? It does work, but it means if you press those buttons while playing then you always do a drift, which feels a little counterintuitive to me.

L and R always do the same thing in Double Dash, right? I haven't played it much.

**Comment by NintendoManiac64** [comment]
The intention is not to use the dpad for steering but to use the dpad for the second co-op player to do a side attack because, with "big L" mapped to items in non-co-op play, you still need some way to do a side attack in co-op play.

This also has the side-benefit of making things easier for much less experienced players in co-op play, whereby they only need to worry about the dpad in order to perform all of their actions and nothing else.

Oh and I realized a bug with the current 2023-10-30 build: It makes the "large" L button on CC/pro act as the GC_L button still while *also* acting as X or Y. I want the "large" L button on CC/pro to *only* act as X or Y to match the controls of basically every other Mario Kart game (except for Super Mario Kart which has L do the same as R, that being jump/slide; MK64 doesn't count due to N64 controller arrangement, but the VC version has L mapped to Z and therefore works as items).

**Comment by libertyernie** [comment]
Yeah, I noticed that bug too - I think this will fix it: https://github.com/libertyernie/Nintendont/commit/b55de50aa2539f00f89547f5dc428742fe96489e#diff-e3e6901e50a638c5361e77f316c581221b73861ce8f28d7fb933f2c911f0cec8R313

So yep, if the intention is for the D-pad to be used just in the menus and by the second co-op player, I think that's fine. I'll put new versions up soon.

**Comment by NintendoManiac64** [comment]
Everything is generally good, except I forgot that L+R isn't just used for random on the character select screen but is also used to pivot/rotate in place at slow speeds (the equivalent of holding A+B in Mario Kart 64). This would probably be best used for the Y button (though it also requires holding A *and* turning at the same time and, due to the placement on the controller, hitting Y+A would be very difficult, so I'm thinking about something fancier).

I'm also thinking about making minus/select be mapped to L+R assuming it doesn't take up too much space now that you've supposedly reintegrated nunchuck control mappings.

Regardless, I've updated the first post accordingly.

**Comment by libertyernie** [comment]
I put the nunchuk controls in the main branch but left them out of the one with Xbox 360 controller support. We have plenty of room for one or the other, just not both

**Comment by NintendoManiac64** [comment]
Build 2023-12-09 works well, though it does do the thing I was a bit concerned about where holding Y does indeed accelerate you forward.

I'm guessing it was too complicated to do the following?:

- Y on CC/pro = GC_L + GC_R

- Y on CC/pro + left analog stick on CC/pro = GC_L + GC_R + GC_A + GC_left-analog-stick

(in other words, when using the left analog stick at the same time as holding Y, just add in `GC_A` rather than doublely-adding GC_L and GC_R)

　
And, while I was a bit late to getting to testing, it's allowed me to find out just last night that there's a 3-4 player grand prix mod that I'll definitely want to take a look at:

- https://www.romhacking.net/hacks/8118/

**Comment by libertyernie** [comment]
I guess it makes sense to only activate A when both Y and a direction are held - I just didn't think of that.

**Comment by NintendoManiac64** [comment]
For context, if you hold GC_L+GC_R without holding A or touching the analog stick during a race, it doesn't really do anything on its own and therefore is quite harmless.

**Comment by NintendoManiac64** [comment]
Two quirks in Navy @ 2023-12-25:

Select/Minus on the CC/pro seems to be incorrectly mapped and is behaving instead as GC_X or GC_Y (don't know which one—I just know that it's making your character use an item). This seemed to have also existed on build 2023-12-09.

The CC_Y button thing works decently well, but it seems that the "pivot" function doesn't actually activate in-game unless you tilt the analog stick to something like 35 or 40%. This is an issue because in the range less than that e.g. 20% tilt, Nintendont is still sending the GC_A button causing you to still accelerate forward rather than pivot.

So the "send GC_A when doing CC_Y+left_analog_x-axis" should only happen if the analog stick is tilted to something like 40%.

...*or*, a crazier idea is that, when holding CC_Y, it actually extends the analog stick's range downward, i.e. anything less 40% analog stick input is actually just treated as 40% regardless anytime you're holding CC_Y.

**Comment by libertyernie** [comment]
What should Select/Minus be instead of X?

For the pivot, maybe I can have it amplify the X axis of the analog stick to a full tilt whenever you hold Y. I bet that would work. Otherwise I'll try those other ideas too.

**Comment by NintendoManiac64** [comment]
> What should Select/Minus be instead of X?

I could have sworn it was GC_Z in older builds, like those from October. I mean, that's the default for these custom builds, is it not?

**Comment by libertyernie** [comment]
Probably, but the top-level post of this issue says "CC/pro_select/minus = GC_X" so I changed it to that.

**Comment by NintendoManiac64** [comment]
> Probably, but the top-level post of this issue says "CC/pro_select/minus = GC_X" so I changed it to that.

...oh, huh. Why did I have it do that...?

Honestly I have no idea why I put that. It just takes up more room in Nintendont does it not (albeit just a teeny bit)? It doesn't really seem to make sense to keep it, so I'll remove it from the top-level post.

**Comment by libertyernie** [comment]
OK, I'll take it out and let it be Z

**Comment by NintendoManiac64** [comment]
The Y button-to-pivot thing works flawlessly in build 2024-01-19
