### ISSUE TITLE
Custom button mapping for Luigi's Mansion

### ISSUE THREAD

**Issue by NintendoManiac64** [libertyernie/Nintendont#8]
- "large" L button on CC pro *only* = GC_R analog press @ 255/255

Due to the mod we've previously done where a digital button press for GC_L and GC_R also sends the corresponding 255/255 analog shoulder button press, you could optionally replace the above `GC_R analog press @ 255/255` with a `GC_R digital press` and it'd still work fine, so if using a digital press saves space then that may actually be more ideal.

- "small" L button on CC pro *only* = GC_L analog press 255/255 (this *must* be an analog press, *not* a digital press!)
- "small" R button on CC pro *only* = GC_L analog press 255/255 (this *must* be an analog press, *not* a digital press!)

- "small" L button on CC pro *only* + "small" R button on CC pro *only* = GC_L digital press

This is the only way I can figure out how to allow the in-game mechanic in a comfortable manner where the GC_L digital press *only* works if the GC_L analog press isn't also pressed to almost full amount.

You can optionally set the GC_L analog press to 25**4**/255 if that's easier on you for whatever reason since that will also work as confirmed with the existing builds.

...also, I previously forgot that non-pro CC already had analog shoulder buttons, but the custom button config stripped that out for Mario Sunshine and Luigi's Mansion. Whoops!

**Comment by libertyernie** [comment]
Should the R button still be a full analog + digital R press?

Also, are there any other button mappings that only need to be applied for the Classic Controller Pro, and not the original Classic Controller? It might make the code easier to maintain.

**Comment by NintendoManiac64** [comment]
> Should the R button still be a full analog + digital R press?

It actually doesn't matter which is why I left it out—no need for a custom mapping for that button when the default should be fine.

> Also, are there any other button mappings that only need to be applied for the Classic Controller Pro, and not the original Classic Controller? It might make the code easier to maintain.

In general it should just be any game that takes advantage of the analog shoulder buttons but in a way that being limited to a half-analog press would be less-than ideal (like is the case in Mario Sunshine where it'd result in a shorter squirt distance), but I don't know of any other games like that (not to say they don't exist however).

**Comment by libertyernie** [comment]
> It actually doesn't matter which is why I left it out—no need for a custom mapping for that button when the default should be fine.

I guess the issue is that I put the default shoulder button mappings before the game-specific mappings, and because there are two different buttons that can trigger an L or R press - and those buttons often do different things in the game-specific mappings - I usually have to blank them out and re-apply them if any of them (L, R, ZL, ZR) have behavior different than the default. Otherwise an R press could still trigger GameCube R, even though R is also mapped now to analog L.

So ideally a custom mapping overrides all of the shoulder buttons (even if it's to do the same thing as default), or none of them. I think that's how I've got them set up right now but I'll check.

**Comment by NintendoManiac64** [comment]
Ohhhh, so that's why the analog functionality of the original classic controllers was lost in the previous build for Mario Sunshine & Luigi's Mansion.

**Comment by libertyernie** [comment]
I just posted a new build where I refactored some things to make the code much more readable - feel free to test it out.

https://github.com/libertyernie/Nintendont/releases/tag/v20231209

**Comment by NintendoManiac64** [comment]
Build 2023-12-09 is good.  While the CC pro-exclusive controls bork with my muscle memory, they are actually usable which is the important part.

I don't think there's anything left to take care of for Luigi's Mansion.
