### ISSUE TITLE
Idea for the "grey" build: have ZL as a copy of Y

### ISSUE THREAD

**Issue by NintendoManiac64** [libertyernie/Nintendont#9]
The idea is that, on a real GC controller, you can hit A and Y at the same time quite easily, but this is not possible on the classic controller.

But since the GameCube also didn't have a ZL button, it could make sense to make that be a copy of the Y button just to help it work as a more generic build (an easy example is GC Metroid Prime/2 where the beam combos require you to press Y while holding A).

In the future I'm thinking about making a suggestion for the Navy build to swap X and Y for a multitude of games.

**Comment by libertyernie** [comment]
Makes sense to me

**Comment by libertyernie** [comment]
I think it's fixed in this build (along with the other open issues): https://github.com/libertyernie/Nintendont/releases/tag/v20240119

**Comment by NintendoManiac64** [comment]
This is indeed present in build 2024-01-19
